// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCg12RSuuIYJEUZazFSF5r2C8knaUfmkw',
    appId: '1:496828677813:web:8bbc8da77017f80cdb48fc',
    messagingSenderId: '496828677813',
    projectId: 'sis-alert-1e7a7',
    authDomain: 'sis-alert-1e7a7.firebaseapp.com',
    storageBucket: 'sis-alert-1e7a7.firebasestorage.app',
    measurementId: 'G-JEH246XMQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoduw8YKW5JWArWZH2dETSElxWEuETF_I',
    appId: '1:496828677813:android:6bae9b32e587b08cdb48fc',
    messagingSenderId: '496828677813',
    projectId: 'sis-alert-1e7a7',
    storageBucket: 'sis-alert-1e7a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgol0vUw-9Em1k3WA2gZsu1PZ8KWycoPU',
    appId: '1:496828677813:ios:7d44619976053e44db48fc',
    messagingSenderId: '496828677813',
    projectId: 'sis-alert-1e7a7',
    storageBucket: 'sis-alert-1e7a7.firebasestorage.app',
    iosBundleId: 'com.example.appAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgol0vUw-9Em1k3WA2gZsu1PZ8KWycoPU',
    appId: '1:496828677813:ios:7d44619976053e44db48fc',
    messagingSenderId: '496828677813',
    projectId: 'sis-alert-1e7a7',
    storageBucket: 'sis-alert-1e7a7.firebasestorage.app',
    iosBundleId: 'com.example.appAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCg12RSuuIYJEUZazFSF5r2C8knaUfmkw',
    appId: '1:496828677813:web:6f446f57eca2cc62db48fc',
    messagingSenderId: '496828677813',
    projectId: 'sis-alert-1e7a7',
    authDomain: 'sis-alert-1e7a7.firebaseapp.com',
    storageBucket: 'sis-alert-1e7a7.firebasestorage.app',
    measurementId: 'G-W3GNZ0LW8C',
  );
}
